ALTER TABLE freight_supplier_bills
  ADD COLUMN IF NOT EXISTS fob_scope text;

CREATE OR REPLACE VIEW active_freight_supplier_bills AS
  SELECT
    id,
    supplier,
    supplier_type,
    bill_month,
    bill_file,
    bl_no,
    container_no,
    cost_category,
    amount,
    currency,
    qty,
    unit_price,
    pair_id,
    rebill_status,
    incoterm,
    link_plan_id,
    link_agency_id,
    reconciled,
    reconcile_note,
    source_row,
    raw,
    created_at,
    updated_at,
    supplier_company_code,
    charge_basis,
    is_standard,
    remarks,
    detention_days,
    payer_company_code,
    sale_amount,
    canonical_category,
    currency_norm,
    govern_flag,
    rebill_to_type,
    rebill_to_name,
    rebill_dn_no,
    rebill_finance_slip_id,
    confirmed_at,
    confirmed_by,
    ap_status,
    ap_paid_amount,
    ap_paid_at,
    ar_status,
    ar_paid_amount,
    ar_paid_at,
    payment_note,
    payment_updated_by,
    payment_updated_at,
    fob_scope
  FROM freight_supplier_bills
  WHERE COALESCE(rebill_status, ''::text) <> 'voided'::text;
