-- M103: Bind manifest header contract onto customs_shipments.
-- Nullable by design: required-field validation stays in business/config layer.

ALTER TABLE customs_shipments
  ADD COLUMN IF NOT EXISTS carrier text,
  ADD COLUMN IF NOT EXISTS cargo_type text,
  ADD COLUMN IF NOT EXISTS transport_terms text,
  ADD COLUMN IF NOT EXISTS payment_method text,
  ADD COLUMN IF NOT EXISTS bl_type text,
  ADD COLUMN IF NOT EXISTS bl_copies integer,
  ADD COLUMN IF NOT EXISTS place_of_issue text,
  ADD COLUMN IF NOT EXISTS payment_place text,
  ADD COLUMN IF NOT EXISTS shipping_agent text,
  ADD COLUMN IF NOT EXISTS shipper_name text,
  ADD COLUMN IF NOT EXISTS shipper_address text,
  ADD COLUMN IF NOT EXISTS shipper_country_code text,
  ADD COLUMN IF NOT EXISTS shipper_phone text,
  ADD COLUMN IF NOT EXISTS shipper_enterprise_code text,
  ADD COLUMN IF NOT EXISTS shipper_aeo_code text,
  ADD COLUMN IF NOT EXISTS consignee_name text,
  ADD COLUMN IF NOT EXISTS consignee_address text,
  ADD COLUMN IF NOT EXISTS consignee_country_code text,
  ADD COLUMN IF NOT EXISTS consignee_phone text,
  ADD COLUMN IF NOT EXISTS consignee_enterprise_code text,
  ADD COLUMN IF NOT EXISTS consignee_aeo_code text,
  ADD COLUMN IF NOT EXISTS consignee_actual_contact text,
  ADD COLUMN IF NOT EXISTS consignee_actual_contact_phone text,
  ADD COLUMN IF NOT EXISTS notify_name text,
  ADD COLUMN IF NOT EXISTS notify_address text,
  ADD COLUMN IF NOT EXISTS notify_country_code text,
  ADD COLUMN IF NOT EXISTS notify_phone text,
  ADD COLUMN IF NOT EXISTS notify_enterprise_code text,
  ADD COLUMN IF NOT EXISTS notify_aeo_code text,
  ADD COLUMN IF NOT EXISTS place_of_receipt text,
  ADD COLUMN IF NOT EXISTS final_destination text;
