-- M104: Order dual identifiers.
-- External number: SE + YYYYMMDD + daily sequence.
-- Internal immutable key: Snowflake-style bigint generated by API.

CREATE TABLE IF NOT EXISTS order_number_sequences (
  prefix text NOT NULL,
  biz_date date NOT NULL,
  last_seq integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (prefix, biz_date)
);

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS public_order_no text,
  ADD COLUMN IF NOT EXISTS internal_snowflake_id bigint;

CREATE UNIQUE INDEX IF NOT EXISTS orders_public_order_no_uidx
  ON orders (public_order_no)
  WHERE public_order_no IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS orders_internal_snowflake_id_uidx
  ON orders (internal_snowflake_id)
  WHERE internal_snowflake_id IS NOT NULL;
