-- Quick Entry missing field_definitions handoff.
-- Human review required before running. No COMMIT in this file.
-- Field id is canonical_key.

-- 1) service_rates truck/customs quick entry fields.
-- Confirm labels, roles, source_column names, required_for_completeness, and layouts before insert.
-- If service_rates already has active field_definitions in production, do not run this block as-is.

INSERT INTO field_definitions (
  canonical_key, module_key, field_key, label, label_cn, type, unit, format, grain,
  input_kind, options_json, validation_json, relationship_json,
  tab, section_key, section_label, section_label_cn, section_order, sort_order,
  editable, visible_roles, editable_roles, col_span,
  source_kind, source_table, source_column, is_system_derived, is_curated, is_legal,
  customs_relevant, stale_risk, show_in_business, show_in_edit, required_for_completeness, status
)
VALUES
  ('service_rates.service', 'service_rates', 'service', 'Service', '服务类型', 'text', NULL, NULL, 'service_rate',
   'select', '["truck","customs"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
   'quick_entry', 'base', 'Base', '基础', 10, 10,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'manual', 'service_rates', 'service', false, true, false,
   false, 'medium', true, true, true, 'active'),
  ('service_rates.price_side', 'service_rates', 'price_side', 'Price side', '成本/销售', 'text', NULL, NULL, 'service_rate',
   'select', '["cost","sell"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
   'quick_entry', 'base', 'Base', '基础', 10, 20,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'manual', 'service_rates', 'price_side', false, true, false,
   false, 'medium', true, true, false, 'active'),
  ('service_rates.executor_company_id', 'service_rates', 'executor_company_id', 'Executor company', '执行公司', 'number', NULL, NULL, 'service_rate',
   'text', NULL, '{}'::jsonb, '{"reference":{"target_table":"companies","target_key_field":"id","target_display_field":"name_cn"}}'::jsonb,
   'quick_entry', 'party', 'Party', '公司归属', 20, 10,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 2,
   'lookup', 'service_rates', 'executor_company_id', false, true, false,
   false, 'medium', true, true, true, 'active'),
  ('service_rates.payable_company_id', 'service_rates', 'payable_company_id', 'Payable company', '付款对象', 'number', NULL, NULL, 'service_rate',
   'text', NULL, '{}'::jsonb, '{"reference":{"target_table":"companies","target_key_field":"id","target_display_field":"name_cn"}}'::jsonb,
   'quick_entry', 'party', 'Party', '公司归属', 20, 20,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 2,
   'lookup', 'service_rates', 'payable_company_id', false, true, false,
   false, 'medium', true, true, false, 'active'),
  ('service_rates.factory_company_id', 'service_rates', 'factory_company_id', 'Factory company', '工厂公司', 'number', NULL, NULL, 'service_rate',
   'text', NULL, '{}'::jsonb, '{"reference":{"target_table":"companies","target_key_field":"id","target_display_field":"name_cn"}}'::jsonb,
   'quick_entry', 'route', 'Route', '路线', 30, 10,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 2,
   'lookup', 'service_rates', 'factory_company_id', false, true, false,
   false, 'medium', true, true, false, 'active'),
  ('service_rates.pol', 'service_rates', 'pol', 'POL', '起运港', 'text', NULL, NULL, 'service_rate',
   'text', NULL, '{}'::jsonb, '{"reference":{"target_table":"ports","target_key_field":"code","target_display_field":"name_cn"}}'::jsonb,
   'quick_entry', 'route', 'Route', '路线', 30, 20,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'lookup', 'service_rates', 'pol', false, true, false,
   false, 'medium', true, true, false, 'active'),
  ('service_rates.pickup_place', 'service_rates', 'pickup_place', 'Pickup place', '提货地', 'text', NULL, NULL, 'service_rate',
   'text', NULL, '{}'::jsonb, '{}'::jsonb,
   'quick_entry', 'route', 'Route', '路线', 30, 30,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'manual', 'service_rates', 'pickup_place', false, true, false,
   false, 'medium', true, true, false, 'active'),
  ('service_rates.customs_port', 'service_rates', 'customs_port', 'Customs port', '报关口岸', 'text', NULL, NULL, 'service_rate',
   'text', NULL, '{}'::jsonb, '{"reference":{"target_table":"ports","target_key_field":"code","target_display_field":"name_cn"}}'::jsonb,
   'quick_entry', 'route', 'Route', '路线', 30, 40,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'lookup', 'service_rates', 'customs_port', false, true, false,
   true, 'medium', true, true, false, 'active'),
  ('service_rates.container_type', 'service_rates', 'container_type', 'Container type', '箱型', 'text', NULL, NULL, 'service_rate',
   'select', '["20GP","40GP","40HQ","45HQ"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
   'quick_entry', 'price', 'Price', '价格', 40, 10,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'manual', 'service_rates', 'container_type', false, true, false,
   false, 'medium', true, true, false, 'active'),
  ('service_rates.rate', 'service_rates', 'rate', 'Rate', '价格', 'number', NULL, 'decimal', 'service_rate',
   'number', NULL, '{"min":0}'::jsonb, '{}'::jsonb,
   'quick_entry', 'price', 'Price', '价格', 40, 20,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'manual', 'service_rates', 'rate', false, true, false,
   false, 'medium', true, true, true, 'active'),
  ('service_rates.currency', 'service_rates', 'currency', 'Currency', '币种', 'text', NULL, NULL, 'service_rate',
   'select', '["CNY","USD"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
   'quick_entry', 'price', 'Price', '价格', 40, 30,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'manual', 'service_rates', 'currency', false, true, false,
   false, 'medium', true, true, false, 'active'),
  ('service_rates.unit', 'service_rates', 'unit', 'Unit', '单位', 'text', NULL, NULL, 'service_rate',
   'text', NULL, '{}'::jsonb, '{}'::jsonb,
   'quick_entry', 'price', 'Price', '价格', 40, 40,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'manual', 'service_rates', 'unit', false, true, false,
   false, 'medium', true, true, false, 'active'),
  ('service_rates.valid_from', 'service_rates', 'valid_from', 'Valid from', '有效期起', 'date', NULL, 'date', 'service_rate',
   'date', NULL, '{}'::jsonb, '{}'::jsonb,
   'quick_entry', 'price', 'Price', '价格', 40, 50,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'manual', 'service_rates', 'valid_from', false, true, false,
   false, 'medium', true, true, false, 'active'),
  ('service_rates.valid_to', 'service_rates', 'valid_to', 'Valid to', '有效期止', 'date', NULL, 'date', 'service_rate',
   'date', NULL, '{}'::jsonb, '{}'::jsonb,
   'quick_entry', 'price', 'Price', '价格', 40, 60,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 1,
   'manual', 'service_rates', 'valid_to', false, true, false,
   false, 'medium', true, true, false, 'active'),
  ('service_rates.notes', 'service_rates', 'notes', 'Notes', '备注', 'text', NULL, NULL, 'service_rate',
   'textarea', NULL, '{}'::jsonb, '{}'::jsonb,
   'quick_entry', 'notes', 'Notes', '备注', 50, 10,
   true, '["admin","logistics"]'::jsonb, '["admin","logistics"]'::jsonb, 4,
   'manual', 'service_rates', 'notes', false, true, false,
   false, 'medium', true, true, false, 'active');

-- 2) Optional layout after field_definitions are confirmed.
INSERT INTO field_layouts (module_key, version, layout_json, status, updated_by)
VALUES (
  'service_rates',
  1,
  '{"sections":[{"key":"base","label":"基础","fields":["service","price_side"]},{"key":"party","label":"公司归属","fields":["executor_company_id","payable_company_id"]},{"key":"route","label":"路线","fields":["factory_company_id","pol","pickup_place","customs_port"]},{"key":"price","label":"价格","fields":["container_type","rate","currency","unit","valid_from","valid_to"]},{"key":"notes","label":"备注","fields":["notes"]}]}'::jsonb,
  'active',
  'handoff'
)
ON CONFLICT DO NOTHING;
